### PR TITLE
Update to Twemoji 12

### PR DESCRIPTION
**Pull request by datitisev**
Closes flarum/core#1811.

- Updated `twemoji` to v12.1.2
- Replaced custom emoji map script with `simple-emoji-map`
    - Same idea
    - Builds map on install, update, or with `npm rebuild simple-emoji-map`
    - Simply require the generated JSON file by importing `simple-emoji-map`
    - Made sure file size is same (with twemoji 11, twemoji 12 adds 4KB) 👌 
    - Reduces source map size lol

### CODE REVIEW

**Comment by franzliedke** [comment]
So how do we ensure an update of the emoji map reaches our dist file?

**Comment by datitisev** [comment]
@franzliedke The emoji map is built when installing dependencies, and is put into a file that is used as the main file for the `simple-emoji-map`  package. 

In other words, JSON map file is generated on packages install. That JSON file is used when importing `simple-emoji-map`.

**Comment by franzliedke** [comment]
I have nothing against merging this, but can you quickly explain the motivation (and why we didn't do it this way until now) for those of us (:raised_back_of_hand:) that don't remember all the back-and-forth?

**Comment by datitisev** [comment]
@franzliedke The only drawback that was mentioned was maintaining the package, but as I'm a core member that shouldn't be a problem (and permission to update can be given to others if needed). 

This also removes the step of having to rebuild the map when a Twemoji update comes out (which we would have to notice). As we have the bot automatically building JS dist files, that means it installs the dependencies on every commit, which builds the emoji map on the latest non-breaking version available.

We didn't do it this way iirc because no one officially agreed to use it, but everyone seemed to agree it was a good idea (or something idk).

Hope that made sense lol.

**Comment by franzliedke** [comment]
Thanks!

**Pull request merged**
