### PR TITLE
Use jsdelivr CDN

### PR DESCRIPTION
**Pull request by wloot**

### CODE REVIEW

**Comment by datitisev** [comment]
Good catch for the actual rendering!

🤔 As this URL repeats a bunch ([here too](https://github.com/flarum/emoji/pull/24/files)), we should probably save it as a constant somewhere... That way we don't have mismatching twemoji versions being used.

This isn't necessarily specific to this PR, but in general... Not asking you to do anything, but just some thoughts that we should probably discuss.

**Comment by wloot** [comment]
> Good catch for the actual rendering!
> 
> 🤔 As this URL repeats a bunch ([here too](https://github.com/flarum/emoji/pull/24/files)), we should probably save it as a constant somewhere... That way we don't have mismatching twemoji versions being used.
> 
> This isn't necessarily specific to this PR, but in general... Not asking you to do anything, but just some thoughts that we should probably discuss.

The version will now be get automatically, correct me if i have some wrong.

**Comment by datitisev** [comment]
Sorry, I didn't intend with my comment that some changes should be made, my apologies for not making that clearer.

The same issue remains (don't make more changes, we need to discuss how we want to approach it) that the same URL is repeated 3 times, with the same logic each time.
We'll want to move these to one place and reference it wherever needed, just not sure where exactly.

Also, the code you added for the version won't work because `regex.exec()` returns a boolean - don't fix it though, we want to discuss stuff first.

**Comment by wloot** [comment]
> Sorry, I didn't intend with my comment that some changes should be made, my apologies for not making that clearer.
> 
> The same issue remains (don't make more changes, we need to discuss how we want to approach it) that the same URL is repeated 3 times, with the same logic each time.
> We'll want to move these to one place and reference it wherever needed, just not sure where exactly.
> 
> Also, the code you added for the version won't work because `regex.exec()` returns a boolean - don't fix it though, we want to discuss stuff first.

`index.js`? and the url in `addComposerAutocomplete.js` has additional "72x72/", so this is needed to extra handle. The current code works to me, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec syas regex.exec() returns an array.

**Comment by datitisev** [comment]
> syas regex.exec() returns an array.

Oh, my bad. Seems like I tested `.test()` instead.

And perhaps index.js. I'm not asking you, it's more for the team to discuss what we want to do. 🙂

**Comment by askvortsov1** [comment]
I also feel kinda weird about repeating this; perhaps we could set it (and export it) somewhere central? Also, is there a reason we need to directly get the file since we have twemoji through npm?

**Comment by datitisev** [comment]
> perhaps we could set it (and export it) somewhere central

Yeah that's what I suggested - wanted some discussion about where first though.

> Also, is there a reason we need to directly get the file since we have twemoji through npm?

❓ What does this mean?

**Comment by tankerkiller125** [comment]
@askvortsov1 The reason not to include the NPM images is because it would drastically increase the shipped size of the emoji extension. Not to mention a CDN is more often than not a faster more reliable way of server a ton of small images.

**Comment by askvortsov1** [comment]
David it means my brain died... 🧠

**Comment by datitisev** [comment]
I made #30 which was merged to replace this one. Thank you for this one though, and my apologies that we didn't really add anything since July.

**Pull request closed without merging**
